FROM alpine
ARG TARGETARCH
ARG TARGETVARIANT

COPY docker-build/nps/${TARGETARCH}${TARGETVARIANT}/nps /nps
COPY conf /conf-tpl
COPY web /web
COPY entrypoint.sh /

RUN chmod +x /nps /entrypoint.sh

VOLUME /conf
EXPOSE 80 443 8080 8024
ENTRYPOINT [ "/entrypoint.sh"]
CMD [ "" ]
